//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTSE_portal.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IPTSEDBEntities : DbContext
    {
        public IPTSEDBEntities()
            : base("name=IPTSEDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IPTSE_Reg_table> IPTSE_Reg_table { get; set; }
        public virtual DbSet<IPTSE_School_Reg_table> IPTSE_School_Reg_table { get; set; }
        public virtual DbSet<login_table> login_table { get; set; }
        public virtual DbSet<payment_details> payment_details { get; set; }
    }
}
