//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTSE_portal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPTSE_Reg_table
    {
        public decimal Id { get; set; }
        public string first_name { get; set; }
        public string mid_name { get; set; }
        public string last_name { get; set; }
        public string gender { get; set; }
        public string addr1 { get; set; }
        public string addr2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zipcode { get; set; }
        public string country { get; set; }
        public string contact { get; set; }
        public string email { get; set; }
        public System.DateTime dob { get; set; }
        public string schoolname { get; set; }
        public string standard { get; set; }
        public string mothername { get; set; }
        public string fathername { get; set; }
        public string volunteername { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public string School_ID { get; set; }
        public string InstitutionType { get; set; }
    }
}
