//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTSE_portal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPTSE_School_Reg_table
    {
        public decimal Id { get; set; }
        public string institution_name { get; set; }
        public string principal_director_name { get; set; }
        public string branch_name { get; set; }
        public string institution_type { get; set; }
        public string addr1 { get; set; }
        public string addr2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zipcode { get; set; }
        public string country { get; set; }
        public string institution_contact { get; set; }
        public string institution_email { get; set; }
        public string contact_person_name { get; set; }
        public string contact_person_contact { get; set; }
        public string contact_person_email { get; set; }
        public string information_source { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
    }
}
