//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTSE_portal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class login_table
    {
        public decimal Id { get; set; }
        public string password { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> LastLoginDateTime { get; set; }
        public string Login_type { get; set; }
    }
}
