//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTSE_portal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment_details
    {
        public decimal Id { get; set; }
        public string payment_id { get; set; }
        public System.DateTime payment_date { get; set; }
        public decimal Amount { get; set; }
    }
}
